name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-multiarch-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        driver-opts: |
          network=host
          image=moby/buildkit:v0.9.3

    - uses: docker/login-action@v3
      with:
        registry: swr.cn-southwest-2.myhuaweicloud.com
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_PASS }}

    - name: Build & Push
      uses: docker/build-push-action@v6    
      with:
        context: ./
        push: true
        platforms: linux/arm64
        tags: |
          swr.cn-southwest-2.myhuaweicloud.com/${{ secrets.NS }}/yum-repo:stable-arm64

    - name: Genarate Dockerfile
      run: |
        cat > Dockerfile << EOF
        FROM swr.cn-southwest-2.myhuaweicloud.com/${{ secrets.NS }}/yum-repo:stable-arm64 as base

        FROM nginx:alpine
        COPY --from=base /usr/share/nginx/html/rpms /usr/share/nginx/html/rpms

        COPY index.html /usr/share/nginx/html
        COPY nginx.conf /etc/nginx/conf.d/default.conf
        EOF

    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        context: ./
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          swr.cn-southwest-2.myhuaweicloud.com/${{ secrets.NS }}/yum-repo:stable


  build-singlearch-image:
    runs-on: ubuntu-latest
    needs: build-multiarch-image
    strategy:
      matrix:
        os: 
          - kylin-V10-sp2
          - kylin-V10
          - openEuler-22
          - openEuler-24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            network=host
            image=moby/buildkit:v0.9.3

      - uses: docker/login-action@v3
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASS }}

      - name: Genarate Dockerfile
        run: |
          cat > Dockerfile << EOF
          FROM swr.cn-southwest-2.myhuaweicloud.com/${{ secrets.NS }}/yum-repo:stable as base

          FROM nginx:alpine
          COPY --from=base /usr/share/nginx/html/rpms/${{ matrix.os }} /usr/share/nginx/html/rpms/${{ matrix.os }}
          COPY --from=base /usr/share/nginx/html/rpms/pypi /usr/share/nginx/html/rpms/pypi

          COPY index.html /usr/share/nginx/html
          COPY nginx.conf /etc/nginx/conf.d/default.conf
          EOF

      - name: Build & Push
        uses: docker/build-push-action@v6    
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            swr.cn-southwest-2.myhuaweicloud.com/${{ secrets.NS }}/yum-repo:${{ matrix.os }}
