name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        driver-opts: network=host

    - uses: docker/login-action@v3
      with:
        registry: swr.cn-southwest-2.myhuaweicloud.com
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_PASS }}

    - name: Build & Push
      uses: docker/build-push-action@v3    
      with:
        context: ./
        push: true
        platforms: linux/arm64
        tags: |
          swr.cn-southwest-2.myhuaweicloud.com/${{ secrets.NS }}/yum-repo:stable